name: INTERFACE-TAG-BASED-DEPLOYMENT

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (qa or prod)"
        required: true
        default: "qa"
      tag:
        description: "Image tag to deploy"
        required: true

jobs:
  deploy:
    name: Deploy to AWS EKS
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_NAME }}

      # Decode ConfigMap from base64 (same way as tracking)
      - name: Write ConfigMap manifest
        run: |
          mkdir -p manifest
          echo "${{ secrets.ENV_FILE_CONTENT }}" | base64 -d > manifest/configmap.yaml
          echo "Generated ConfigMap:"
          cat manifest/configmap.yaml

      # Update Deployment manifest
      - name: Update Deployment Manifest
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.event.inputs.tag }}
        run: |
          envsubst < manifest/interface.yaml > manifest/interface-updated.yaml
          echo "Updated deployment manifest:"
          cat manifest/interface-updated.yaml

      # Deploy to AWS EKS
      - name: Deploy to AWS EKS
        env:
          EKS_CLUSTER_NAME: ${{ github.event.inputs.environment == 'prod' && secrets.EKS_CLUSTER_NAME_PROD || secrets.EKS_CLUSTER_NAME }}
        run: |
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region ${{ secrets.AWS_REGION_NAME }}
          kubectl apply -f manifest/configmap.yaml
          kubectl apply -f manifest/interface-updated.yaml
          # Force restart so new config is picked up
          kubectl rollout restart deployment interface
          sleep 10
          kubectl get pods | grep interface
